### ISSUE TITLE
Additional instruction columns in instruction sheet

### ISSUE THREAD

**Issue by wonkoderverstaendige** [fpbattaglia/obj_scorer#5]
The instruction sheet needs additional columns/a generic instruction column in key:val format to convey additional information for trials, like duration, pre- or post-trial conditions like novelty, etc.

**Comment by fpbattaglia** [comment]
The possibility to change trial duration is added as of 5bb8d96fefd013261cbbf83928446799c2a6a77c 
Now the csv sheet may include a column 'trial_duration' which should specify trial duration as an integer number of seconds. 
If that columns is missing, it will fall back to the value in the JSON config file. 
Note that now in the JSON config file the property is now called "default_trial_duration_seconds" instead of "trial_duration seconds"

**Comment by fpbattaglia** [comment]
Added a post-trial dialog showing instructions as of a8e10c03685efa5aa63a08de0e04aed52b291260
